# This config is a STUB! This should never be generated.
# Use the default lua config from https://github.com/hyprwm/Hyprland/blob/main/example/hyprland.lua

source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/lookandfeel.conf
source = ~/.config/hypr/env.conf
source = ~/.config/hypr/autostartup.conf



xwayland {
    force_zero_scaling = true
} 
